/* GENERATED by gir/subclass — DO NOT EDIT */

#include <pango/pango.h>
#include <moonbit.h>
#include <stdint.h>
#include <string.h>

typedef struct _MotivaPangoSvgRenderer MotivaPangoSvgRenderer;
typedef struct _MotivaPangoSvgRendererClass MotivaPangoSvgRendererClass;

typedef struct MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box {
  MotivaPangoSvgRenderer *value;
} MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box;

typedef struct MoonBitPangoGlyphItem MoonBitPangoGlyphItem;
typedef struct MoonBitPangoFont MoonBitPangoFont;
typedef struct MoonBitPangoAttrShape MoonBitPangoAttrShape;

typedef struct MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box {
  PangoRenderer *value;
} MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box;

struct _MotivaPangoSvgRenderer {
  /* GObject instance inheritance is C struct embedding: the immediate parent must be first. */
  PangoRenderer parent_instance;
  /* One retained MoonBit state value is shared by every selected vfunc. */
  void *moonbit_state;
  void (*moonbit_renderer_prepare_run)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoGlyphItem *, void *);
  void (*moonbit_renderer_draw_glyph_item)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, moonbit_bytes_t, int32_t, MoonBitPangoGlyphItem *, int32_t, int32_t, void *);
  void (*moonbit_renderer_draw_rectangle)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, int32_t, void *);
  void (*moonbit_renderer_draw_error_underline)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, void *);
  void (*moonbit_renderer_draw_trapezoid)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, double, double, double, double, double, double, void *);
  void (*moonbit_renderer_draw_glyph)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoFont *, uint32_t, double, double, void *);
  void (*moonbit_renderer_draw_shape)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoAttrShape *, int32_t, int32_t, void *);
};

struct _MotivaPangoSvgRendererClass {
  /* The class struct follows the same single-inheritance prefix rule. */
  PangoRendererClass parent_class;
};

G_DEFINE_TYPE(MotivaPangoSvgRenderer, motiva_pango_native_renderer_motiva_pango_svg_renderer, pango_renderer_get_type())

static int32_t
motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_from_native(PangoRenderPart value) {
  if (value == (PangoRenderPart)PANGO_RENDER_PART_FOREGROUND)
    return 0;
  if (value == (PangoRenderPart)PANGO_RENDER_PART_BACKGROUND)
    return 1;
  if (value == (PangoRenderPart)PANGO_RENDER_PART_UNDERLINE)
    return 2;
  if (value == (PangoRenderPart)PANGO_RENDER_PART_STRIKETHROUGH)
    return 3;
  if (value == (PangoRenderPart)PANGO_RENDER_PART_OVERLINE)
    return 4;
  return 0;
}

static PangoRenderPart
motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_to_native(int32_t value) {
  switch (value) {
  case 0:
    return (PangoRenderPart)PANGO_RENDER_PART_FOREGROUND;
  case 1:
    return (PangoRenderPart)PANGO_RENDER_PART_BACKGROUND;
  case 2:
    return (PangoRenderPart)PANGO_RENDER_PART_UNDERLINE;
  case 3:
    return (PangoRenderPart)PANGO_RENDER_PART_STRIKETHROUGH;
  case 4:
    return (PangoRenderPart)PANGO_RENDER_PART_OVERLINE;
  default:
    g_critical("motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_to_native: unsupported MoonBit enum value %d\n", value);
    return (PangoRenderPart)PANGO_RENDER_PART_FOREGROUND;
  }
}

static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run)(PangoRenderer *, PangoLayoutRun*) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item)(PangoRenderer *, const char*, PangoGlyphItem*, int, int) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle)(PangoRenderer *, PangoRenderPart, int, int, int, int) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline)(PangoRenderer *, int, int, int, int) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid)(PangoRenderer *, PangoRenderPart, double, double, double, double, double, double) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph)(PangoRenderer *, PangoFont*, PangoGlyph, double, double) = NULL;
static void (*motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape)(PangoRenderer *, PangoAttrShape*, int, int) = NULL;

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_box_destroy(void *box) {
  /* Every generated MoonBit object box contains exactly one GObject pointer. */
  GObject **object = (GObject **)box;
  if (*object != NULL)
    g_object_unref(*object);
}

static MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box *
motiva_pango_native_renderer_motiva_pango_svg_renderer_box_create_owned(MotivaPangoSvgRenderer *value) {
  if (value == NULL)
    return NULL;
  /* Adopt g_object_new's existing reference. Only floating instances need to be sunk. */
  if (g_object_is_floating(value))
    g_object_ref_sink(value);
  MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box *box = (MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box *)moonbit_make_external_object(
    motiva_pango_native_renderer_motiva_pango_svg_renderer_box_destroy, sizeof(MotivaPangoSvgRenderer *)
  );
  box->value = value;
  return box;
}

static MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *
motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(PangoRenderer *value) {
  if (value == NULL)
    return NULL;
  /* A reverse callback receives a borrowed native pointer, so its MoonBit box owns a new reference. */
  MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *box = (MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *)moonbit_make_external_object(
    motiva_pango_native_renderer_motiva_pango_svg_renderer_box_destroy, sizeof(PangoRenderer *)
  );
  box->value = (PangoRenderer *)g_object_ref(value);
  return box;
}

/* Callback parameters share the ordinary binding ABI prefix: the native pointer is the first field. */
/* The callback box owns a reference or copy, so MoonBit may retain it after the native virtual method returns. */
static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_glyph_item_destroy(void *box) {
  PangoGlyphItem **pointer = (PangoGlyphItem **)box;
  if (*pointer == NULL)
    return;
  g_boxed_free(pango_glyph_item_get_type(), *pointer);
}

static MoonBitPangoGlyphItem *
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_glyph_item_wrap(PangoGlyphItem *value) {
  if (value == NULL)
    return NULL;
  MoonBitPangoGlyphItem *box = (MoonBitPangoGlyphItem *)moonbit_make_external_object(
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_glyph_item_destroy, sizeof(PangoGlyphItem *)
  );
  *((PangoGlyphItem **)box) = (PangoGlyphItem *)g_boxed_copy(pango_glyph_item_get_type(), value);
  return box;
}

/* Callback parameters share the ordinary binding ABI prefix: the native pointer is the first field. */
/* The callback box owns a reference or copy, so MoonBit may retain it after the native virtual method returns. */
static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_font_destroy(void *box) {
  PangoFont **pointer = (PangoFont **)box;
  if (*pointer == NULL)
    return;
  g_object_unref(*pointer);
}

static MoonBitPangoFont *
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_font_wrap(PangoFont *value) {
  if (value == NULL)
    return NULL;
  MoonBitPangoFont *box = (MoonBitPangoFont *)moonbit_make_external_object(
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_font_destroy, sizeof(PangoFont *)
  );
  *((PangoFont **)box) = (PangoFont *)g_object_ref(value);
  return box;
}

/* Callback parameters share the ordinary binding ABI prefix: the native pointer is the first field. */
/* The callback box owns a reference or copy, so MoonBit may retain it after the native virtual method returns. */
static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_attr_shape_destroy(void *box) {
  PangoAttrShape **pointer = (PangoAttrShape **)box;
  if (*pointer == NULL)
    return;
  pango_attribute_destroy((PangoAttribute *)*pointer);
}

static MoonBitPangoAttrShape *
motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_attr_shape_wrap(PangoAttrShape *value) {
  if (value == NULL)
    return NULL;
  MoonBitPangoAttrShape *box = (MoonBitPangoAttrShape *)moonbit_make_external_object(
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_attr_shape_destroy, sizeof(PangoAttrShape *)
  );
  *((PangoAttrShape **)box) = (PangoAttrShape *)pango_attribute_copy((const PangoAttribute *)value);
  return box;
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_prepare_run_trampoline(PangoRenderer *object, PangoLayoutRun* run) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoGlyphItem *, void *) = self->moonbit_renderer_prepare_run;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run(object, run);
    return;
  }
  MoonBitPangoGlyphItem *run_wrapped = motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_glyph_item_wrap((PangoGlyphItem *)run);
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), run_wrapped, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_glyph_item_trampoline(PangoRenderer *object, const char* text, PangoGlyphItem* glyph_item, int x, int y) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, moonbit_bytes_t, int32_t, MoonBitPangoGlyphItem *, int32_t, int32_t, void *) = self->moonbit_renderer_draw_glyph_item;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item(object, text, glyph_item, x, y);
    return;
  }
  int32_t text_has = text != NULL ? 1 : 0;
  moonbit_bytes_t text_bytes = NULL;
  if (text != NULL) {
    int32_t text_length = (int32_t)strlen(text);
    text_bytes = moonbit_make_bytes(text_length, 0);
    memcpy(text_bytes, text, text_length);
  }
  MoonBitPangoGlyphItem *glyph_item_wrapped = motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_glyph_item_wrap((PangoGlyphItem *)glyph_item);
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), text_bytes, text_has, glyph_item_wrapped, (int32_t)x, (int32_t)y, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_rectangle_trampoline(PangoRenderer *object, PangoRenderPart part, int x, int y, int width, int height) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, int32_t, void *) = self->moonbit_renderer_draw_rectangle;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle(object, part, x, y, width, height);
    return;
  }
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_from_native(part), (int32_t)x, (int32_t)y, (int32_t)width, (int32_t)height, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_error_underline_trampoline(PangoRenderer *object, int x, int y, int width, int height) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, void *) = self->moonbit_renderer_draw_error_underline;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline(object, x, y, width, height);
    return;
  }
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), (int32_t)x, (int32_t)y, (int32_t)width, (int32_t)height, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_trapezoid_trampoline(PangoRenderer *object, PangoRenderPart part, double y1_, double x11, double x21, double y2, double x12, double x22) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, double, double, double, double, double, double, void *) = self->moonbit_renderer_draw_trapezoid;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid(object, part, y1_, x11, x21, y2, x12, x22);
    return;
  }
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_from_native(part), (double)y1_, (double)x11, (double)x21, (double)y2, (double)x12, (double)x22, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_glyph_trampoline(PangoRenderer *object, PangoFont* font, PangoGlyph glyph, double x, double y) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoFont *, uint32_t, double, double, void *) = self->moonbit_renderer_draw_glyph;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph(object, font, glyph, x, y);
    return;
  }
  MoonBitPangoFont *font_wrapped = motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_font_wrap((PangoFont *)font);
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), font_wrapped, (uint32_t)glyph, (double)x, (double)y, state);
  moonbit_decref(state);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_shape_trampoline(PangoRenderer *object, PangoAttrShape* attr, int x, int y) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  void (*callback)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoAttrShape *, int32_t, int32_t, void *) = self->moonbit_renderer_draw_shape;
  if (state == NULL || callback == NULL) {
    /* Construction and repeated disposal can observe an empty MoonBit state; preserve parent behavior in that window. */
    if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape != NULL)
      motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape(object, attr, x, y);
    return;
  }
  MoonBitPangoAttrShape *attr_wrapped = motiva_pango_native_renderer_motiva_pango_svg_renderer_parameter_pango_attr_shape_wrap((PangoAttrShape *)attr);
  /* The MoonBit method may release the last external object box and run dispose. Keep state alive until it returns. */
  moonbit_incref(state);
  callback(motiva_pango_native_renderer_motiva_pango_svg_renderer_wrap_renderer_borrowed(object), attr_wrapped, (int32_t)x, (int32_t)y, state);
  moonbit_decref(state);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, MoonBitPangoGlyphItem * run) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run(object->value, (PangoLayoutRun*)(*((PangoGlyphItem **)run)));
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, moonbit_bytes_t text_bytes, int32_t text_has, MoonBitPangoGlyphItem * glyph_item, int32_t x, int32_t y) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item(object->value, text_has != 0 ? (const char*)text_bytes : NULL, (PangoGlyphItem*)(*((PangoGlyphItem **)glyph_item)), (int)x, (int)y);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, int32_t part, int32_t x, int32_t y, int32_t width, int32_t height) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle(object->value, (PangoRenderPart)motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_to_native(part), (int)x, (int)y, (int)width, (int)height);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, int32_t x, int32_t y, int32_t width, int32_t height) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline(object->value, (int)x, (int)y, (int)width, (int)height);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, int32_t part, double y1_, double x11, double x21, double y2, double x12, double x22) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid(object->value, (PangoRenderPart)motiva_pango_native_renderer_motiva_pango_svg_renderer_pango_render_part_to_native(part), (double)y1_, (double)x11, (double)x21, (double)y2, (double)x12, (double)x22);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, MoonBitPangoFont * font, uint32_t glyph, double x, double y) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph(object->value, (PangoFont*)(*((PangoFont **)font)), (PangoGlyph)glyph, (double)x, (double)y);
}

MOONBIT_FFI_EXPORT
void
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *object, MoonBitPangoAttrShape * attr, int32_t x, int32_t y) {
  /* Explicit chain-up calls the implementation saved before class_init installed the MoonBit trampoline. */
  if (object == NULL || object->value == NULL)
    return;
  if (motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape != NULL)
    motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape(object->value, (PangoAttrShape*)(*((PangoAttrShape **)attr)), (int)x, (int)y);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_dispose(GObject *object) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)object;
  void *state = self->moonbit_state;
  /* Clear fields first: dispose is allowed to run more than once and releasing state can execute MoonBit finalizers. */
  self->moonbit_state = NULL;
  self->moonbit_renderer_prepare_run = NULL;
  self->moonbit_renderer_draw_glyph_item = NULL;
  self->moonbit_renderer_draw_rectangle = NULL;
  self->moonbit_renderer_draw_error_underline = NULL;
  self->moonbit_renderer_draw_trapezoid = NULL;
  self->moonbit_renderer_draw_glyph = NULL;
  self->moonbit_renderer_draw_shape = NULL;
  if (state != NULL)
    moonbit_decref(state);
  G_OBJECT_CLASS(motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_class)->dispose(object);
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_class_init(MotivaPangoSvgRendererClass *klass) {
  GObjectClass *object_class = G_OBJECT_CLASS(klass);
  object_class->dispose = motiva_pango_native_renderer_motiva_pango_svg_renderer_dispose;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_prepare_run = ((PangoRendererClass *)g_type_class_peek_parent(klass))->prepare_run;
  ((PangoRendererClass *)klass)->prepare_run = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_prepare_run_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph_item = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_glyph_item;
  ((PangoRendererClass *)klass)->draw_glyph_item = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_glyph_item_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_rectangle = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_rectangle;
  ((PangoRendererClass *)klass)->draw_rectangle = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_rectangle_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_error_underline = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_error_underline;
  ((PangoRendererClass *)klass)->draw_error_underline = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_error_underline_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_trapezoid = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_trapezoid;
  ((PangoRendererClass *)klass)->draw_trapezoid = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_trapezoid_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_glyph = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_glyph;
  ((PangoRendererClass *)klass)->draw_glyph = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_glyph_trampoline;
  motiva_pango_native_renderer_motiva_pango_svg_renderer_parent_renderer_draw_shape = ((PangoRendererClass *)g_type_class_peek_parent(klass))->draw_shape;
  ((PangoRendererClass *)klass)->draw_shape = motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_draw_shape_trampoline;
}

static void
motiva_pango_native_renderer_motiva_pango_svg_renderer_init(MotivaPangoSvgRenderer *self) {
  self->moonbit_state = NULL;
  self->moonbit_renderer_prepare_run = NULL;
  self->moonbit_renderer_draw_glyph_item = NULL;
  self->moonbit_renderer_draw_rectangle = NULL;
  self->moonbit_renderer_draw_error_underline = NULL;
  self->moonbit_renderer_draw_trapezoid = NULL;
  self->moonbit_renderer_draw_glyph = NULL;
  self->moonbit_renderer_draw_shape = NULL;
}

MOONBIT_FFI_EXPORT
MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_Box *
moonbit_motiva_pango_native_renderer_motiva_pango_svg_renderer_new(
  void (*renderer_prepare_run)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoGlyphItem *, void *),
  void (*renderer_draw_glyph_item)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, moonbit_bytes_t, int32_t, MoonBitPangoGlyphItem *, int32_t, int32_t, void *),
  void (*renderer_draw_rectangle)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, int32_t, void *),
  void (*renderer_draw_error_underline)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, int32_t, int32_t, int32_t, void *),
  void (*renderer_draw_trapezoid)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, int32_t, double, double, double, double, double, double, void *),
  void (*renderer_draw_glyph)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoFont *, uint32_t, double, double, void *),
  void (*renderer_draw_shape)(MoonBit_motiva_pango_native_renderer_motiva_pango_svg_renderer_renderer_Box *, MoonBitPangoAttrShape *, int32_t, int32_t, void *),
  void *state
) {
  MotivaPangoSvgRenderer *self = (MotivaPangoSvgRenderer *)g_object_new(motiva_pango_native_renderer_motiva_pango_svg_renderer_get_type(), NULL);
  self->moonbit_state = state;
  if (state != NULL)
    moonbit_incref(state); /* retained until dispose */
  self->moonbit_renderer_prepare_run = renderer_prepare_run;
  self->moonbit_renderer_draw_glyph_item = renderer_draw_glyph_item;
  self->moonbit_renderer_draw_rectangle = renderer_draw_rectangle;
  self->moonbit_renderer_draw_error_underline = renderer_draw_error_underline;
  self->moonbit_renderer_draw_trapezoid = renderer_draw_trapezoid;
  self->moonbit_renderer_draw_glyph = renderer_draw_glyph;
  self->moonbit_renderer_draw_shape = renderer_draw_shape;
  return motiva_pango_native_renderer_motiva_pango_svg_renderer_box_create_owned(self);
}
